[package]
name = "timekeeper-infra-postgres"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
timekeeper-app = { path = "../app" }
timekeeper-domain = { path = "../domain" }
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
tracing = "0.1"
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
